"""Add new columns to company_financials and stock_news

Revision ID: 0bf134316b30
Revises: 
Create Date: 2024-07-31 11:55:28.262354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bf134316b30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financials', sa.Column('acceptance_datetime', sa.DateTime(), nullable=True))
    op.add_column('company_financials', sa.Column('timeframe', sa.String(), nullable=False))
    op.add_column('company_financials', sa.Column('tickers', sa.String(), nullable=False))
    op.add_column('company_financials', sa.Column('sic', sa.Integer(), nullable=False))
    op.add_column('stock_news', sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_news', 'insights')
    op.drop_column('company_financials', 'sic')
    op.drop_column('company_financials', 'tickers')
    op.drop_column('company_financials', 'timeframe')
    op.drop_column('company_financials', 'acceptance_datetime')
    # ### end Alembic commands ###
